version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "11472:3306"
    volumes:
      - $docker_data_dir/jaspercarwash/:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "11470:80"
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: nginx-html
    restart: always
    ports:
      - "11471:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./html/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php


  php:
    build: ./api
    container_name: php-backend
    restart: always
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql
