
services:
  mysql:
    image: mysql:8
    container_name: jasper_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    # ports:
      # - "3306:3306"
    volumes:
      - $docker_data_dir/jaspercarwash/:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: jasper_nginx
    restart: always
    ports:
      - "11471:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jasper_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "11470:80"
    depends_on:
      - mysql
  api:
    build: 
      context: ./apiv2
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: Europe/Amsterdam
      DB_PATH: /data/database.db
    ports:
      - "11472:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/openapi.json"]
      interval: 30s
      start_period: 5s
      timeout: 5s
      retries: 3
