version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: jasper_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  php:
    image: php:8.2-fpm
    container_name: jasper_php
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./api:/var/www/html/api
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: jasper_nginx
    restart: always
    ports:
      - "11471:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jasper_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "11470:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
